name: Tests

on: [push, pull_request]

jobs:
  run:
    name: PHP ${{ matrix.php-version }}
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with: 
          php-version: ${{ matrix.php-version }}
          coverage: none
          
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
                  
      - name: Install Composer dependencies
        run: composer install
        
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
